<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit7e78b974c5a60c1892ae9c9ae7654fe0
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PopupMaker\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PopupMaker\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit7e78b974c5a60c1892ae9c9ae7654fe0', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PopupMaker\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit7e78b974c5a60c1892ae9c9ae7654fe0', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PopupMaker\Vendor\Composer\Autoload\ComposerStaticInit7e78b974c5a60c1892ae9c9ae7654fe0::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
